In [13]:
import pandas as pd 
import numpy as np 
import seaborn as sns


In [15]:
from scipy.stats import zscore
data=sns.load_dataset('iris')
df=data.copy()


In [17]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [19]:
zscore(df.drop('species',axis=1))


sepal_length  sepal_width  petal_length  petal_width
0       -0.900681     1.019004     -1.340227    -1.315444
1       -1.143017    -0.131979     -1.340227    -1.315444
2       -1.385353     0.328414     -1.397064    -1.315444
3       -1.506521     0.098217     -1.283389    -1.315444
4       -1.021849     1.249201     -1.340227    -1.315444
..            ...          ...           ...          ...
145      1.038005    -0.131979      0.819596     1.448832
146      0.553333    -1.282963      0.705921     0.922303
147      0.795669    -0.131979      0.819596     1.053935
148      0.432165     0.788808      0.933271     1.448832
149      0.068662    -0.131979      0.762758     0.790671

[150 rows x 4 columns]

In [35]:
z_scores = np.abs(zscore(df.drop('species',axix=1)))


TypeError: DataFrame.drop() got an unexpected keyword argument 'axix'

A
0   10
1   12
2   15
3  100
4   18
5   20
6   22
7  105

In [33]:
from scipy import stats
import pandas as pd

# Example DataFrame
data = {'A': [10, 12, 15, 100, 18, 20, 22, 105]}  # Contains outliers
df = pd.DataFrame(data)

# Compute Z-scores
z_score = stats.zscore(df)

# Identify outliers (absolute Z-score >= 3)
outliers = (abs(z_score) >= 3).any(axis=1)

# Select rows that are outliers
outliers_rows = df[outliers]

print(outliers_rows)


Empty DataFrame
Columns: [A]
Index: []


In [43]:
(z_scores<=3).all(axis=1)

NameError: name 'z_scores' is not defined

In [45]:
from sklearn.ensemble import IsolationForest
import seaborn as sns
import numpy as np
import pandas as pd





In [47]:
data = sns.load_dataset('iris')
data


sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [49]:
data.head(3)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [51]:
from sklearn.preprocessing import LabelEncoder 
lb=LabelEncoder()
data['species']=lb.fit_transform(data['species'])



In [53]:
clf=IsolationForest(random_state=10)
clf.fit(data)


IsolationForest(random_state=10)

In [55]:
clf.predict(data)

array([ 1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1, -1, -1, -1,
        1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1, -1,
        1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,
       -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [57]:
y_hat=clf.predict(data)
y_hat


array([ 1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1, -1, -1, -1,
        1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1, -1,
        1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,
       -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [63]:
y_hat[y_hat==-1]

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1])

In [65]:
np.where(y_hat==-1)

(array([  5,   8,  13,  14,  15,  16,  18,  22,  23,  24,  32,  33,  41,
         43,  44,  50,  52,  57,  60,  62,  70,  93,  98, 100, 105, 106,
        107, 108, 109, 114, 117, 118, 119, 122, 125, 129, 130, 131, 134,
        135, 136], dtype=int64),)

In [67]:
idc=np.where(y_pred_outliers==-1)
idx[0]

NameError: name 'y_pred_outliers' is not defined