In [1]:
import numpy as np

In [2]:
array[]

SyntaxError: invalid syntax (<ipython-input-2-023ab13a96a2>, line 1)

In [ ]:
array[row_start: row_end : row_step, col_start: col_end:col_step]

In [ ]:
array([[44,68,58,65,64,54,24,58],
       [35,89,87,45,65,74,12,52],
       [96,56,36,95,22,15,32,51],
       [12,13,16,17,18,19,15,11],
       [77,88,99,44,55,66,22,33],
       [41,65,54,21,36,45,65,44],
       [12,13,16,17,18,19,15,11],
       [44,68,58,65,64,54,24,58]])

In [3]:
import pandas as pd

In [4]:
k=       [96,56,36,95,22,15,32,51]
k

[96, 56, 36, 95, 22, 15, 32, 51]

In [6]:


np.array(k)

array([96, 56, 36, 95, 22, 15, 32, 51])

In [8]:
pd.Series(k)

0    96
1    56
2    36
3    95
4    22
5    15
6    32
7    51
dtype: int64

AttributeError: 'list' object has no attribute 'shape'

In [14]:
t=[[44,68],
       [35,89],
       [96,56],
       [12,13],
       [77,88],
       [41,65],
       [12,13],
       [44,68]]

In [15]:
t

[[44, 68],
 [35, 89],
 [96, 56],
 [12, 13],
 [77, 88],
 [41, 65],
 [12, 13],
 [44, 68]]

In [16]:
g=np.array(t)

In [17]:
g

array([[44, 68],
       [35, 89],
       [96, 56],
       [12, 13],
       [77, 88],
       [41, 65],
       [12, 13],
       [44, 68]])

In [21]:
pd.DataFrame(t,columns=['name,'sub'], index=[125,445,390,378,354,326,459,454])

SyntaxError: invalid syntax (<ipython-input-21-1a5095c1a7b6>, line 1)